# Generated by Django 6.1.1 on 2026-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('course_image', models.ImageField(null=True, upload_to='media/course_image')),
                ('course_fee', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
