# Generated by Django 6.1.1 on 2026-10-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='category',
            field=models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL')], max_length=100, null=True),
        ),
    ]
