# Generated by Django 6.1.1 on 2026-10-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150, null=True)),
                ('stu_class', models.CharField(max_length=50, null=True)),
                ('stu_roll', models.PositiveIntegerField(null=True)),
                ('stu_image', models.ImageField(null=True, upload_to='media/stu_image')),
                ('select', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], max_length=50, null=True)),
            ],
        ),
    ]
