# Generated by Django 6.1.1 on 2026-10-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stumodel',
            name='publish_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
