# Generated by Django 6.1.2 on 2026-10-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_alter_categorymodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='expired_date',
            field=models.DateField(null=True),
        ),
    ]
