# Generated by Django 6.1.1 on 2026-09-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('address', models.TextField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
