# Generated by Django 6.1.1 on 2026-09-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=254),
        ),
    ]
