# Generated by Django 6.1.2 on 2026-10-08 06:34

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_datetime', models.DateTimeField(null=True)),
                ('expense_amount', models.PositiveIntegerField(null=True)),
                ('expense_description', models.TextField(null=True)),
                ('expense_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageCash.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='AddCashModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=150, null=True)),
                ('cash_datetime', models.DateTimeField(null=True)),
                ('cash_amount', models.PositiveIntegerField(null=True)),
                ('cash_description', models.TextField(null=True)),
                ('cash_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ManageCash.usermodel')),
            ],
        ),
    ]
