# Generated by Django 6.1.1 on 2026-10-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcashmodel',
            name='cash_datetime',
        ),
        migrations.RemoveField(
            model_name='expensemodel',
            name='expense_datetime',
        ),
        migrations.AddField(
            model_name='addcashmodel',
            name='datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='datetime',
            field=models.DateField(null=True),
        ),
    ]
