# Generated by Django 6.1.1 on 2026-10-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0002_remove_addcashmodel_cash_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcashmodel',
            old_name='datetime',
            new_name='cash_datetime',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='datetime',
            new_name='expense_datetime',
        ),
    ]
