# Generated by Django 6.1.1 on 2026-10-08 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0003_rename_datetime_addcashmodel_cash_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcashmodel',
            old_name='cash_datetime',
            new_name='datetime',
        ),
        migrations.RenameField(
            model_name='expensemodel',
            old_name='expense_datetime',
            new_name='datetime',
        ),
    ]
