# Generated by Django 6.1.1 on 2026-10-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManageCash', '0004_rename_cash_datetime_addcashmodel_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcashmodel',
            name='datetime',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
