# Generated by Django 6.1.1 on 2026-10-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('author_name', models.CharField(max_length=150, null=True)),
                ('content', models.TextField(null=True)),
                ('blog_image', models.ImageField(null=True, upload_to='media/blog_image')),
                ('publish_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
