# Generated by Django 6.1.1 on 2026-09-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
