# Generated by Django 6.1.1 on 2026-09-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('product_date', models.DateField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/product_img')),
            ],
        ),
    ]
