# Generated by Django 6.1.1 on 2026-09-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productmodel_created_at_productmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='gender',
            field=models.CharField(choices=[('fruits', 'Fruits'), ('grocery', 'Grocery'), ('fashion', 'Fashion')], max_length=20, null=True),
        ),
    ]
