# Generated by Django 6.1.1 on 2026-09-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productmodel_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='gender',
            new_name='product_type',
        ),
    ]
