# Generated by Django 6.1.1 on 2026-10-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('Vendor', 'Vendor'), ('Customer', 'Customer')], max_length=150, null=True),
        ),
    ]
