# Generated by Django 6.1.1 on 2026-10-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_usermodel_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofilemodel',
            old_name='customer_description',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customerprofilemodel',
            old_name='customer_phone',
            new_name='phone',
        ),
    ]
