# Generated by Django 6.1.1 on 2026-10-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_rename_customer_description_customerprofilemodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofilemodel',
            name='user_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
