# Generated by Django 6.1.1 on 2026-09-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150, null=True)),
                ('c_description', models.TextField(null=True)),
                ('course_image', models.ImageField(null=True, upload_to='media/course_img')),
            ],
        ),
        migrations.CreateModel(
            name='DeptModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=150, null=True)),
                ('d_description', models.TextField(null=True)),
                ('dept_head', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150, null=True)),
                ('marks', models.PositiveIntegerField(null=True)),
                ('grade', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=150, null=True)),
                ('stu_image', models.ImageField(null=True, upload_to='media/stu_img')),
                ('admission_date', models.DateField(null=True)),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('course_fee', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
