# Generated by Django 6.1.1 on 2026-09-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='project_status',
            field=models.CharField(choices=[('NotStarted', 'NotStarted'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
